[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hrmelt"
version = "0.1.0"
description = "MeltwaterBench Deep learning for spatiotemporal downscaling of surface meltwater"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools]
packages = ["hrmelt"]

[tool.setuptools.package-data]
hrmelt = [
    "**/*"
]

[tool.ruff]
line-length = 120
target-version = "py312"
fix = true
show-fixes = true
exclude = ["data/*","notebooks/*","references/*","runs/*"]

[tool.ruff.lint]
select = ["E", "F", "I", "W"]
ignore = ["F841"] # During development, disable fix for unused variables 
# ignore = ["E501", "W291"]  # ignore long lines and trailing whitespace

[tool.ruff.format]
quote-style = "single"
skip-magic-trailing-comma = false