epochs: [500] # Running more epochs to make sure bigger models will also train
batch_size: [8] # Currently not varying over batch size, because I'm unsure how batch norm behaves during validation
img_size: [[512,512]] # [[32,32], [128,128], [256,256], [512,512]] # height, width
optimizer: ['adam']
learning_rate: [0.0001, 0.001, 0.01]  # Learning rate
lr_patience: [100]
weight_decay: [0.00001, 0.]
loss_function: ['l1', 'mse'] # Currently only using l1, because I'm using validation loss to find best model
activation: ['gelu', 'relu'] # Only gelu and relu are implemented
num_extra_convs: [0]
num_workers: [18]
out_activation: ['sigmoid']
period_wandb_full_scale_im: [10] # To reduce storage on wandb during sweep
log_inputs_and_targets_to_wandb: [False] # To reduce storage on wandb during sweep

# 3 * 2 * 2 * 2 = 24