loss_function: ['l1'] # 'mse','nnlloss'] # Currently only using l1, because I'm using validation loss to find best model
num_workers: [18]
epochs: [101]
learning_rate: [2., 1., 0.1, 0.01] # see if the learning rate still has to be optimized
weight_decay: [0.]
optimizer: ['adam']
# comparing baseline to different atrous rates to get a better understanding
lr_scheduler: [ReduceLROnPlateau] # using new cosine annealing to se if the model avoids local minima better
lr_patience: [5]
out_activation: ['tanhshelf'] # 'sigmoid', 'sigmoidcutoff', 'tanhshelf'
seed: [41,42]
period_wandb_full_scale_im: [5] # To reduce storage on wandb during sweep
log_inputs_and_targets_to_wandb: [False] # To reduce storage on wandb during sweep

# 4 * 2 = 8